development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  host: <%= ENV.fetch("CABLE_HOST") { "redis" } %>
  port: <%= ENV.fetch("CABLE_PORT") { "6379" }.to_i %>
  db: <%= ENV.fetch("CABLE_DB") { "2" }.to_i %>
  username: <%= ENV.fetch("CABLE_USERNAME") { "default" } %>
  password: <%= ENV.fetch("CABLE_PASSWORD") { "insecure-password" } %>
