services:
  app:
    container_name: decidim
    image: ${DECIDIM_IMAGE:-"decidim/decidim:latest"}
    command: "bin/rails server -b 0.0.0.0"
    entrypoint: ["/code/entrypoint.sh"]
    pull_policy: always
    restart: always
    expose:
      - 3000
    volumes:
      - ${PWD}/Gemfile.wrapper:/code/Gemfile.wrapper
      - ${PWD}/Gemfile.local:/code/Gemfile.local
      - ${PWD}/scripts/entrypoint.sh:/code/entrypoint.sh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`$DECIDIM_DOMAIN`)"
      - "traefik.http.routers.app.entrypoints=web,websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
    env_file:
      - .env
    environment:
      - BUNDLE_GEMFILE=Gemfile.wrapper
      - DATABASE_URL
      - SECRET_KEY_BASE
      - DECIDIM_FORCE_SSL=${DECIDIM_FORCE_SSL:-false}
      - QUEUE_ADAPTER=${QUEUE_ADAPTER:-sidekiq}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-2}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DECIDIM_ENABLE_HTML_HEADER_SNIPPETS
      - DECIDIM_ADMIN_PASSWORD_EXPIRATION_DAYS=${DECIDIM_ADMIN_PASSWORD_EXPIRATION_DAYS:-360}
      - CHANGE_ACTIVE_STEP=${CHANGE_ACTIVE_STEP:-enabled}
      - SEND_REMINDERS=${SEND_REMINDERS:-enabled}
      - WEEKLY_NOTIFICATIONS_DIGEST=${WEEKLY_NOTIFICATIONS_DIGEST:-enabled}
      - DAILY_NOTIFICATIONS_DIGEST=${DAILY_NOTIFICATIONS_DIGEST:-enabled}
      - HEALTHCHECK_EXCLUDE_CHECKS=${HEALTHCHECK_EXCLUDE_CHECKS:-emailconf}
      - SMTP_STARTTLS_AUTO=${SMTP_STARTTLS_AUTO:-true}
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_ADDRESS
      - SMTP_DOMAIN
      - SMTP_PORT
      - DECIDIM_MAILER_SENDER
      - MAPS_API_KEY
      - MAPS_PROVIDER=${MAPS_PROVIDER:-here}
      - RACK_ATTACK_SECRET
