version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - run:
          name: Install Bash
          command: |
            apk add --no-cache bash
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      - run:
          name: Pull images
          command: |
            docker pull decidim/decidim:latest || true
            docker pull decidim/decidim:latest-dev || true
            docker pull decidim/decidim:latest-deploy || true
      - run:
          name: Set decidim version
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              echo 'latest' > release_tag
            else
              echo $CIRCLE_BRANCH > release_tag
            fi

            echo Set tag: $(cat release_tag)
      - run:
          name: Build docker images
          command: |
            export RELEASE_TAG=$(cat release_tag)

            docker build -f Dockerfile \
                         -t decidim/decidim:$RELEASE_TAG \
                         -t decidim/decidim:$RELEASE_TAG-$CIRCLE_SHA1 \
                         -t decidim/decidim:latest \
                         --cache-from=decidim/decidim:latest .

            docker build -f Dockerfile-dev \
                         --build-arg base_image_tag=$RELEASE_TAG-$CIRCLE_SHA1 \
                         -t decidim/decidim:$RELEASE_TAG-dev \
                         -t decidim/decidim:$RELEASE_TAG-dev-$CIRCLE_SHA1 \
                         -t decidim/decidim:latest-dev \
                         --cache-from=decidim/decidim:latest-dev .

            docker build -f Dockerfile-deploy \
                         --build-arg base_image_tag=$RELEASE_TAG-$CIRCLE_SHA1 \
                         -t decidim/decidim:$RELEASE_TAG-deploy \
                         -t decidim/decidim:$RELEASE_TAG-deploy-$CIRCLE_SHA1 \
                         -t decidim/decidim:latest-deploy \
                         --cache-from=decidim/decidim:latest-deploy .

      - run:
          name: Push application Docker image
          shell: /bin/bash
          command: |
            export RELEASE_TAG=$(cat release_tag)

            if [[ "${RELEASE_TAG}" == "latest" || "${RELEASE_TAG}" =~ ^v[0-9\.]+$ ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push decidim/decidim:$RELEASE_TAG
              docker push decidim/decidim:$RELEASE_TAG-dev
              docker push decidim/decidim:$RELEASE_TAG-deploy
            fi
