version: 2
jobs:
  build:
    working_directory: /app
    environment:
      - DECIDIM_VERSION=0.13.1
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - run:
          name: Install Bash & Curl
          command: |
            apk add --no-cache bash curl curl-dev
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build images
          command: scripts/build_images.sh
      - run:
          name: Push images
          command: scripts/push_images.sh
