version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/decidim.tar
            - /caches/decidim-dev.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/decidim.tar | true
            docker load -i /caches/decidim-dev.tar | true
      - run:
          name: Set decidim version
          run: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'latest' > release_tag
            else
              echo $CIRCLE_BRANCH > release_tag
            fi
      - run:
          name: Build docker images
          command: |
            export RELEASE_TAG=`cat release_tag`

            docker build -f Dockerfile \
                         --build-arg decidim_version=$RELEASE_TAG \
                         -t decidim/decidim:$RELEASE_TAG-$CIRCLE_SHA1 \
                         -t decidim/decidim:$RELEASE_TAG \
                         -t decidim/decidim:latest \
                         --cache-from=decidim/decidim:latest .

            docker build -f Dockerfile-dev \
                         --build-arg decidim_version=$RELEASE_TAG \
                         --build-arg base_image_tag=$RELEASE_TAG-$CIRCLE_SHA1 \
                         -t decidim/decidim:$RELEASE_TAG-dev \
                         -t decidim/decidim:$RELEASE_TAG-dev-$CIRCLE_SHA1 \
                         -t decidim/decidim:dev-latest \
                         --cache-from=decidim/decidim:dev-latest .

      - deploy:
          name: Push application Docker image
          command: |
            export RELEASE_TAG=`cat release_tag`

            if [[ "${RELEASE_TAG}" == "latest" || "${RELEASE_TAG}" =~ ^v([0-9]\.?)+$ ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push decidim/decidim:$RELEASE_TAG
              docker push decidim/decidim:dev-$RELEASE_TAG
            fi

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/decidim.tar decidim/decidim:latest
            docker save -o /caches/decidim-dev.tar decidim/decidim:dev-latest
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/decidim.tar
            - /caches/decidim-dev.tar
