version: 2
jobs:
  build:
    working_directory: /app
    environment:
      - DECIDIM_VERSION=0.7.4
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - run:
          name: Install Bash
          command: |
            apk add --no-cache bash
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      - run:
          name: Pull images
          command: |
            docker pull decidim/decidim:latest || true
            docker pull decidim/decidim:latest-dev || true
            docker pull decidim/decidim:latest-deploy || true
      - run:
          name: Build docker images
          shell: /bin/bash
          command: |
            set -e
            docker build -f Dockerfile \
                        --build-arg decidim_version=$DECIDIM_VERSION \
                        -t decidim/decidim:$CIRCLE_SHA1 \
                        --cache-from=decidim/decidim:latest .

            docker build -f Dockerfile-dev \
                        --build-arg base_image_tag=$CIRCLE_SHA1 \
                        --build-arg decidim_version=$DECIDIM_VERSION \
                        -t decidim/decidim:$CIRCLE_SHA1-dev \
                        --cache-from=decidim/decidim:latest-dev .

            docker build -f Dockerfile-deploy \
                        --build-arg base_image_tag=$CIRCLE_SHA1 \
                        -t decidim/decidim:$CIRCLE_SHA1-deploy \
                        --cache-from=decidim/decidim:latest-deploy .

      - run:
          name: Push application Docker image
          shell: /bin/bash
          command: |
            set -e
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS

              docker tag decidim/decidim:$CIRCLE_SHA1-deploy decidim/decidim:latest-deploy
              docker tag decidim/decidim:$CIRCLE_SHA1-dev decidim/decidim:latest-dev
              docker tag decidim/decidim:$CIRCLE_SHA1 decidim/decidim:latest

              docker push decidim/decidim:$latest-deploy
              docker push decidim/decidim:$latest-dev
              docker push decidim/decidim:$latest
            fi

            if [[ "${CIRCLE_BRANCH}" =~ ^[0-9\.]+$ ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS

              docker tag decidim/decidim:$CIRCLE_SHA1-deploy decidim/decidim:$CIRCLE_BRANCH-deploy
              docker tag decidim/decidim:$CIRCLE_SHA1-dev decidim/decidim:$CIRCLE_BRANCH-dev
              docker tag decidim/decidim:$CIRCLE_SHA1 decidim/decidim:$CIRCLE_BRANCH

              docker push decidim/decidim:$CIRCLE_BRANCH-deploy
              docker push decidim/decidim:$CIRCLE_BRANCH-dev
              docker push decidim/decidim:$CIRCLE_BRANCH
            fi
