version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - run:
          name: Install Bash
          command: |
            apk add --no-cache bash
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      - run:
          name: Pull images
          command: |
            docker pull decidim/decidim:latest || true
            docker pull decidim/decidim:latest-dev || true
            docker pull decidim/decidim:latest-deploy || true
      - run:
          name: Build docker images
          shell: /bin/bash
          command: |
            cat versions.txt | sort -r -n | while read version; do
              docker build -f Dockerfile \
                          --build-arg decidim_version=$version \
                          -t decidim/decidim:$version \
                          -t decidim/decidim:$version-$CIRCLE_SHA1 \
                          -t decidim/decidim:latest \
                          --cache-from=decidim/decidim:latest .

              docker build -f Dockerfile-dev \
                          --build-arg base_image_tag=$version-$CIRCLE_SHA1 \
                          --build-arg decidim_version=$version \
                          -t decidim/decidim:$version-dev \
                          -t decidim/decidim:$version-dev-$CIRCLE_SHA1 \
                          -t decidim/decidim:latest-dev \
                          --cache-from=decidim/decidim:latest-dev .

              docker build -f Dockerfile-deploy \
                          --build-arg base_image_tag=$version-$CIRCLE_SHA1 \
                          -t decidim/decidim:$version-deploy \
                          -t decidim/decidim:$version-deploy-$CIRCLE_SHA1 \
                          -t decidim/decidim:latest-deploy \
                          --cache-from=decidim/decidim:latest-deploy .
            done

      - run:
          name: Push application Docker image
          shell: /bin/bash
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push decidim/decidim:latest

              cat versions.txt | while read version; do
                docker push decidim/decidim:$version
                docker push decidim/decidim:$version-dev
                docker push decidim/decidim:$version-deploy
              done
            fi
