services:
  app:
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER:-decidim}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-decidim}
      POSTGRES_DB: ${DATABASE_NAME:-decidim}
