ARG base_image=decidim/decidim:latest

FROM $base_image
LABEL maintainer="info@codegram.com"

ARG decidim_version

RUN git clone https://github.com/rubygems/rubygems /tmp/rubygems \
  && cd /tmp/rubygems \
  && git checkout e093fb7d594f97edaa6289547a90537871ca5f98 \
  && git submodule update --init \
  && ruby setup.rb \
  && rm -rf /tmp/rubygems

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install -y google-chrome-stable

RUN CHROMEDRIVER_RELEASE=2.35 \
  && CHROMEDRIVER_URL="http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
  && apt-get install unzip \
  && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip $CHROMEDRIVER_URL \
  && unzip /tmp/chromedriver_linux64.zip chromedriver -d /usr/local/bin \
  && rm /tmp/chromedriver_linux64.zip

RUN DOCKERIZE_VERSION=v0.6.0 \
  && wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN gem install decidim-dev:$decidim_version

ENTRYPOINT []
