ARG base_image_tag

FROM decidim/decidim:$base_image_tag
MAINTAINER info@codegram.com

ARG decidim_version
ENV DECIDIM_VERSION=$decidim_version

RUN apt-get update && apt-get install -y chromium chromium-chromedriver
RUN apt-get update && apt-get install -y wget

ENV DOCKERIZE_VERSION v0.5.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN gem install decidim-dev -v $DECIDIM_VERSION

ENTRYPOINT []
