ARG base_image_tag=latest

FROM decidim/decidim:$base_image_tag
MAINTAINER info@codegram.com

ENV RAILS_ENV=production
ENV PORT=3000

RUN cd /tmp && decidim test_app && rm -fR test_app

ONBUILD COPY Gemfile Gemfile.lock ./
ONBUILD RUN bundle install
ONBUILD COPY . .
ONBUILD RUN bundle install
ONBUILD RUN bundle exec rake assets:precompile

ENTRYPOINT []
ENV RAILS_SERVE_STATIC_FILES=true
CMD bundle exec rails s
