ARG base_image=decidim/decidim:0.22.0-test

FROM $base_image
LABEL maintainer="info@coditramuntana.com"

RUN apt-get install -y sudo \
  && apt-get clean

RUN adduser --shell /bin/bash --disabled-password --gecos "" decidim \
  && adduser decidim sudo \
  && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN echo 'Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bundle/bin"' > /etc/sudoers.d/secure_path
RUN chmod 0440 /etc/sudoers.d/secure_path

COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT []
