ARG base_image=ghcr.io/decidim/decidim-generator:latest

FROM $base_image
LABEL maintainer="info@coditramuntana.com"

ARG decidim_version=0.23.1

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install -y google-chrome-stable \
  && apt-get clean

RUN CHROMEDRIVER_RELEASE=85.0.4183.87 \
  && CHROMEDRIVER_URL="http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
  && apt-get install unzip \
  && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip $CHROMEDRIVER_URL \
  && unzip /tmp/chromedriver_linux64.zip chromedriver -d /usr/local/bin \
  && rm /tmp/chromedriver_linux64.zip

RUN DOCKERIZE_VERSION=v0.6.1 \
  && wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN gem install decidim-dev:${decidim_version} --force

ENTRYPOINT []
