ARG ruby_version=2.7.5

FROM ruby:${ruby_version}
LABEL maintainer="hola@decidim.org"

ARG decidim_version=0.26.2

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

WORKDIR /code

RUN apt-get install -y git imagemagick wget \
  && apt-get clean

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - \
  && apt-get install -y nodejs \
  && apt-get clean

RUN npm install -g npm@7.21.1
RUN npm install -g yarn@1.22.18

RUN gem install bundler --version '>= 2.3.12' \
  && gem install decidim:${decidim_version} --no-document

CMD ["decidim"]

ENTRYPOINT []
