ARG ruby_version=3.3.4

FROM ruby:${ruby_version}
LABEL maintainer="hola@decidim.org"

ARG decidim_version=30.2
ARG node_version=18

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

WORKDIR /code

RUN apt-get update && apt-get install -y git imagemagick p7zip wget \
  && apt-get clean

RUN curl -sL https://deb.nodesource.com/setup_${node_version}.x | bash - \
  && apt-get install -y nodejs libclang-dev \
  && apt-get clean

RUN npm install -g yarn@1.22.18

RUN gem install bundler --version '>= 2.3.12' \
  && gem install decidim:${decidim_version} --no-document

CMD ["decidim"]

ENTRYPOINT []
