version: '3'
services:
  nginx:
    image: nginx:1.23.1-alpine
    volumes:
      - public-files:/home/decidim/app/public:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - decidim
  decidim:
    environment:
      - RAILS_SERVE_STATIC_FILES=false
    volumes:
      - public-files:/home/decidim/app/public
    networks:
      - private

volumes:
  public-files: {}
