
version: '3'
services:
  decidim:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DECIDIM_VERSION=0.27.0
        - NODE_VERSION=16.9.1
        - ALPINE_RUBY_VERSION=3.0

