
version: '3'
services:
  decidim:
    build:
      context: ./bundle
      dockerfile: ./Dockerfile
      args:
        - DECIDIM_VERSION=0.26.4
        - NODE_VERSION=16.9.1
        - RUBY_VERSION=2.7.5
    depends_on:
      - pg
      - redis
      - mailer
      - decidim-migrate
    environment:
      - RAILS_SERVE_STATIC_FILES=true

  decidim-migrate:
    command: bundle exec rails db:migrate
    image: ghcr.io/decidim/decidim:latest
    build:
      context: ./bundle
      dockerfile: ./Dockerfile
      args:
        - DECIDIM_VERSION=0.26.4
        - NODE_VERSION=16.9.1
        - RUBY_VERSION=2.7.5
    