
version: '3'
services:
  decidim:
    entrypoint: ""
    build:
      context: ./bundle
      dockerfile: ./Dockerfile
      args:
        - DECIDIM_VERSION=0.27.1
        - NODE_VERSION=16.9.1
        - RUBY_VERSION=3.0
        - BUNDLER_VERSION=2.3.20

