services:
  app:
    depends_on:
      - cache
  cache:
    image: redis:8-alpine
    container_name: decidim_cache
    volumes:
      - redis_data:/data
    restart: always
volumes:
  redis_data: {}
