services:
  worker:
    image: ${DECIDIM_IMAGE:-decidim/decidim:latest}
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    entrypoint: ["/code/sidekiq_entrypoint.sh"]
    pull_policy: always
    restart: always
    env_file:
      - .env
    volumes:
      - ${PWD}/Gemfile.wrapper:/code/Gemfile.wrapper
      - ${PWD}/Gemfile.local:/code/Gemfile.local
      - ${PWD}/scripts/sidekiq_entrypoint.sh:/code/sidekiq_entrypoint.sh
    environment:
      - BUNDLE_GEMFILE
      - DATABASE_URL
      - SECRET_KEY_BASE
      - DECIDIM_FORCE_SSL=false
      - QUEUE_ADAPTER=sidekiq
      - REDIS_URL=redis://redis:6379/1
    links:
      - cache
