#! /bin/bash
set -e
# Remove pid file if exists
PID_FILE=${RAILS_PID_FILE:-"tmp/pids/server.pid"}
if [[ -f ${PID_FILE} ]]; then
	echo "Removing pid file ${PID_FILE}"
	rm -f "${PID_FILE}"
fi

# Wait for postgres to be available for connections
echo "Waiting for database, cache and job databases."
wait-for-it -h "${DATABASE_HOST:-db}" -p "${DATABASE_PORT:-5432}" -t 60
if [ -z ${CACHE_HOST+x} ];
then
	wait-for-it -h "${CACHE_HOST:-redis}" -p "${CACHE_PORT:-6379}" -t 60
fi
if [ -z ${JOB_HOST+x} ];
then
	wait-for-it -h "${JOB_HOST:-redis}" -p "${JOB_PORT:-6379}" -t 60
fi

bundle check

if [ ! -f $ROOT/.app_seeded ]; then
	echo "Seed the application"
	bundle exec rails decidim:seed
	touch .app_seeded
fi
echo "Running '$@'"
# All looks great, can execute commands
exec "$@"
