#!/bin/bash
RUN_PUMA="false"
RUN_SIDEKIQ="false"

if [[ ${DECIDIM_RUN_PUMA} == "1" ]]; then
	RUN_PUMA="true"
fi

if [[ ${DECIDIM_RUN_SIDEKIQ} == "1" ]]; then
	RUN_SIDEKIQ="true"
fi

export RUN_PUMA=$RUN_PUMA
export RUN_SIDEKIQ=$RUN_SIDEKIQ

touch /home/decidim/app/supervisord.conf
(envsubst \$RUN_PUMA,\$RUN_SIDEKIQ </ etc/supervisord.template) > /home/decidim/app/config/supervisord.conf
envsubst \$ROOT,\$DECIDIM_VERSION < /etc/motd.template) > /etc/motd
supervisord -c /home/decidim/app/config/supervisord.conf
