name: Build docker images

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'bundle/Dockerfile-*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish images
        run: |
          ./update
          for file in $(find bundle -type f -name "Dockerfile-*"); do
            tag=$(basename "$file" | sed 's/^Dockerfile-//')
            echo "build 'decidim/$tag' with bundle/$file"
            docker build -t decidim/"$tag":"${{ github.sha }}" -f "$file" .
            docker push decidim/"$tag":"${{ github.sha }}"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update files from update script"
          git push
